name: CI

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the current directory
        run: ls -R  # This will help verify the directory structure

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your required Java version
          distribution: 'temurin'  # or 'zulu', depending on your preference

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./my-app  # Adjust this path based on your repo structure

      - name: Archive WAR file
        run: |
          mv ./my-app/target/*.war ./myapp.war  # Adjust based on the output path of the WAR file

      - name: Deploy to Tomcat
        run: |
          curl -u nausher:123456 --upload-file ./myapp.war http://3.110.184.47:9090/manager/text/deploy?path=/my-app&update=true
