name: CI

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your required Java version

      - name: Build with Maven
        run: mvn clean install  # Adjust this to your build command
