name: CI

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your required Java version
          distribution: 'temurin'  # or 'zulu', depending on your preference

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./  # Ensure this is set to the root where pom.xml is located

      - name: Archive WAR file
        run: |
          mv target/*.war ./myapp.war  # Adjust if necessary based on actual WAR file name
        shell: bash

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST http://3.110.184.47:8080/job/GitTomcat/ \
          --user nausher:token1234
      - name: Print working directory and list files
        run: |
          pwd
          ls -R
