name: CI

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your required Java version
          distribution: 'temurin'  # or 'zulu', depending on your preference

      - name: Build with Maven
        run: mvn clean package
        working-directory: /opt/tomcat/conf/my-app  # Set the working directory to the location of your pom.xml

      - name: Archive WAR file
        run: |
          mv target/*.war ./myapp.war  # Adjust the path based on your project structure
        shell: bash

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST http://3.110.184.47:8080/job/GitTomcat/ \
          --user nausher:token1234
