name: CI

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or your required Java version
          distribution: 'temurin'  # or 'zulu', depending on your preference

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./opt/apache-tomcat-9.0.95/conf/my-app  # Adjust this path to where your pom.xml is located

      - name: Archive WAR file
        run: |
          mv ./opt/apache-tomcat-9.0.95/conf/my-app/target/*.war ./myapp.war  # Adjust the path based on your project structure

      - name: Deploy to Tomcat
        run: |
          curl -u nausher:123456 --upload-file ./myapp.war http://3.110.184.47:9090/manager/text/deploy?path=/my-app&update=true
